CREATE TABLE FINANCIAL_ANALYSIS
(
    ID                    NUMBER(19,0) PRIMARY KEY,
    COMPANY_NAME          VARCHAR2(255),
    COMPANY_SYMBOL        VARCHAR2(255),
    COMPANY_SECTOR        VARCHAR2(255),
    COMPANY_EXCHANGE      VARCHAR2(255),
    REPORTING_PERIOD      VARCHAR2(255),
    CURRENCY              VARCHAR2(255),
    MARKET_CAP            NUMBER(19,4),
    REVENUE               NUMBER(19,4),
    NET_INCOME            NUMBER(19,4),
    OPERATING_CASH_FLOW   NUMBER(19,4),
    FREE_CASH_FLOW        NUMBER(19,4),
    EPS                   NUMBER(19,4),
    ROE                   NUMBER(19,4),
    DEBT_TO_EQUITY        NUMBER(19,4),
    EXECUTIVE_SUMMARY     CLOB,
    INVESTMENT_THESIS     CLOB,
    STRENGTHS             CLOB,
    RISKS                 CLOB,
    GROWTH_SIGNALS        CLOB,
    WARNING_SIGNALS       CLOB,
    INVESTMENT_OPINION    VARCHAR2(255),
    CONFIDENCE_LEVEL      NUMBER(19,4),
    UNIT                  VARCHAR2(255),
    AUDITED               NUMBER(1,0),
    SOURCE_LANGUAGE       VARCHAR2(255),
    EXTRACTION_CONFIDENCE NUMBER(19,4)
);

CREATE SEQUENCE FINANCIAL_ANALYSIS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;